### PR TITLE
Import games/caesar and games/rot13

### PR DESCRIPTION
**Pull request by Tookmund**

### CODE REVIEW

**Comment by tcort** [comment]
I think you'll need to add entries to distrib/sets/lists/minix/mi for these too.

**Comment by Tookmund** [comment]
Whoops! I keep forgetting about that!

**Comment by Tookmund** [comment]
My branch for this has been updated, but for some reason the pull request will not update

**Comment by sambuc** [comment]
Submitted as:
  http://gerrit.minix3.org/2985

**Pull request closed without merging**
