### PR TITLE
servers/(vfs + is): K&R C -> ANSI C

### PR DESCRIPTION
**Pull request by richi235**
Aditionally this removes all trailing whitespaces using: 
`sed -i 's/[[:space:]]*$//' *.c`

I used the same tools and config as in my K&R pull request in July.

### CODE REVIEW

**Comment by dcvmoole** [comment]
My apologies that this is taking a while; I have a branch with a *lot* of changes to VFS right now, and before passing on this patch I'd like to make sure it doesn't create massive conflicts. I hope you don't mind. It has not been forgotten!

**Comment by richi235** [comment]
@dcvmoole thanks for the note, good to know.

### And an maybe helpful info for you concerning your vfs changes:
I did this conversion using an existing tool and a self written perl script. Not manually.
Which means now (after figuring out the tool config + my script) it's not much work for me
to create a conversion patch for all .c files in a directory. 

Therefore you can also change this PR and notice me again if your VFS branch is merged.
Then I could run my tools again and create a new PR.
This way may be much easier and avoid lots of conflicts.

**Comment by dcvmoole** [comment]
That's cool, thanks - however I also don't want my private/future stuff to get in the way of others committing things right now, so I just wanted to assess quickly how bad it would be and that took a bit longer than expected, that's all! In any case it does not look like this is generating many conflicts so I'm more than happy to merge it now.

For what it's worth: as I also wrote in a google group post just now, the MINIX3 network stack will be replaced soon, so if you are willing to continue working on these types of changes (which would be much appreciated!) please do skip the inet service altogether, and perhaps for now also the network drivers. Everything else should be fair game right now :)

**Comment by dcvmoole** [comment]
Actually let me add that we'd also like to avoid creating conflicts for pull request #134 for the time being if at all possible..

**Comment by dcvmoole** [comment]
Merged as 4aa48abab95b2c3bef55ef84ec4b7c49368fb6f8 and a0814afb2e128f52ed10c9a5d4c91bf6abc22290, thank you!

**Pull request closed without merging**
