### PR TITLE
Add the driver for VIA Technology 6105/6106S Ethernet card

### PR DESCRIPTION
**Pull request by XidianGeneral**
The new driver is referred to Minix 3.4.0 rtl8169 driver and Linux 4.2.1 via-rhine driver.
The PCI number is 1106:3106:1186:1403.

### CODE REVIEW

**Comment by dcvmoole** [comment]
That looks really, really good. Just to make absolutely sure I just have to ask one thing, because you mention using Linux as reference: is your driver indeed BSD licensed, and entirely free of GPL code? If so, we'll be happy to merge this right away!

**Comment by XidianGeneral** [comment]
Thanks, I am very happy to hear that :)
Yes, the driver code is free of GPL. If the code has any problem, please feel free to contact me.

**Comment by dcvmoole** [comment]
Excellent, thank you very much! I have slightly amended your patch to build and install the driver by default - that way it is also built as part of the integration testing, which is what the patch is going through now. If everything goes well, the actual merging may take a little bit longer, due to planned absence of the other MINIX3 reviewer (to summarize that very quickly).

**Comment by XidianGeneral** [comment]
This is a README file for this driver.

**Comment by dcvmoole** [comment]
Cool! I've forwarded the two new patches to the testing system as well.

**Comment by dcvmoole** [comment]
Merged as 022136b354f57076feaa8f0ae820cd578efdbad0, 9784113fda0dc424347489f1b8e8e77961d4e756, and e154914956380951cb5da405c38cd6d15f7e532a - thank you!

**Pull request closed without merging**
