### PR TITLE
PXE boot generation script

### PR DESCRIPTION
**Pull request by boricj**
This adds turn-key PXE booting to MINIX using SYSLINUX.

As discussed in #63, this will require a Git repository for SYSLINUX over at http://git.minix3.org before merging. For now, a personal repository (https://github.com/boricj/syslinux) is used.

### CODE REVIEW

**Comment by sambuc** [comment]
Hi @boricj,

While merging the NetBSD source tree with ours, I realized that we did not import completely the NetBSD boot loader.

Mainly in ``sys/arch/i386/stand/``, there is a ``pxeboot`` folder. Could this be used instead of the syslinux blobs?

Regards,

Lionel

**Comment by boricj** [comment]
It looks like the standard NetBSD bootloader modified to work in a PXE environment. I'll give it a try.

**Comment by boricj** [comment]
Well, it requires libkern and I just realized that porting libkern isn't trivial enough for this pull request.

I can't spare time to port libkern (and by extension the NetBSD PXE boot loader) for now, so I see four options :
 1. bundle binary blobs of the NetBSD PXE boot loader, built with a NetBSD tree (untested), solving the license issue ;
 2. stick with the pull request as it is and promote PXELINUX to the same status as U-Boot ;
 3. drop PXELINUX, write the required steps to PXE boot on the wiki (and lose the QEMU one-liner) ;
 4. wait and keep this whole thing unofficial until further notice.

This choice is not mine to make, but I'll check option 1 in the meantime.

**Comment by boricj** [comment]
QEMU's limited built-in DHCP server prevents NetBSD's pxeboot from reading ``boot.cfg``, so it is impossible to create a PXE boot one-liner for QEMU. Also, I failed to boot MINIX with the built-in prompt, but I can't rule out an error on my end.

That doesn't prevent in theory booting MINIX using pxeboot with another emulator or a physical setup, but with the end of my school holidays I really can't investigate this any further. It's PXELINUX or bust :-(

**Comment by boricj** [comment]
With boot-to-ramdisk pull request #120 merged, I documented the required steps to achieve PXE boot on the wiki (http://wiki.minix3.org/doku.php?id=usersguide:bootingovernetworkusingpxe).

Thus, there's no reason to keep this pull request open anymore as `releasetools/x86_ramdisk.sh` can be used to create a suitable image.

**Pull request closed without merging**
