### PR TITLE
Fixed tiny spelling error in proc.c

### PR DESCRIPTION
**Pull request by taigrr**
an returned -> and returned

### CODE REVIEW

**Comment by taigrr** [comment]
This only affects a docstring.

**Comment by taigrr** [comment]
:(

**Comment by sambuc** [comment]
Why are you sad? Your kind contribution was merged.

**Comment by taigrr** [comment]
Oh, that's very odd. GitHub must have a bug. Here's what I see.
image

**Comment by sambuc** [comment]
The reason is GitHub is not the primary source for the sources of Minix. This is Gerrit, which allows us to enforce pre-commit tests, and as long as those do not pass successfully we cannot merge commits. This helps us ensure the master branch is at all time correct.

To track revision of a patch as it is being worked on, Gerrit needs an ID to be added in the commit message. In order to add that ID, I have to amend the commit message, which generates a new hash for the commit. This is why GitHub does not see your commit as merged, because its commit ID has changed.

This is the only downside of the process so far.

**Comment by taigrr** [comment]
Ah okay, makes sense. Nice to know a little more about the process too! Thanks

**Pull request closed without merging**
