### PR TITLE
minor changes regarding (U)EFI

### PR DESCRIPTION
**Pull request by rlfnb**
minor mistake made before, its now part of local jenkins.
If its more convenient, feel free to close it as the same commit is part of the libacpi PR as well.

### CODE REVIEW

**Comment by dcvmoole** [comment]
This is rather vague. "the" bug? Ideally commit messages (even if not fully on the first line) explain what's going on without relying on the reader being aware of external context. Imagine someone reading this in five years. Then again I already don't know what's going on here right now..

**Comment by rlfnb** [comment]
changed the description, is it for for integrating now?

**Comment by rlfnb** [comment]
changed commit message, maybe its ready to commit now?

**Comment by boricj** [comment]
@dcvmoole said in #140 that 1c25730 would cause buffer underflows in the serial lines. If that's the case this particular commit is unlikely to be accepted.

**Comment by dcvmoole** [comment]
The commit message is better but there is still quite some room for improvement, so let me elaborate. Keep in mind: the commit message is not for you to be done with the patch, but for others to read later, possibly much later, and assess primarily whether this patch is of interest to the reader, who will typically care about some patches only, and secondarily what was changed and why. Ideally the first (title) line of the commit message captures both points. As such, a good commit title gives at least some indication of the subsystem affected by the change whenever possible - the MINIX3 source code tree is a big place - and some description that allows the reader to establish the high-level goal of the change, without looking at the patch itself. On top of that, the title line should be no more than 52 characters, as per the general rules for git commit messages which the MINIX3 project has adopted as well: http://wiki.minix3.org/doku.php?id=developersguide:commitmessages . That restriction ensures the title line is not getting cut off in various places (eg gitweb).

As such, a better commit title for this patch would be something like "releasetools: fix, update GRUB source retrieval". For now I'll take this patch as is, but please do keep in mind the above points going forward.

The tty patch will indeed not be merged and never will be, for the same reason as last time.

**Comment by dcvmoole** [comment]
Merged as 702ec7400fb0580bac51ffbb217dd5d2b097d4d6, thank you!

**Pull request closed without merging**
