### PR TITLE
mined: minor clean-ups

### PR DESCRIPTION
**Pull request by tcort**

### CODE REVIEW

**Comment by sambuc** [comment]
Hi @tcort,

The changes are submitted:
   http://gerrit.minix3.org/2970 mined.h: remove minix/config.h include.        
   http://gerrit.minix3.org/2971 mined.h: remove unused definition, MEMORY_SIZE.        
   http://gerrit.minix3.org/2972 mined.h: remove irrlevant comment.        
   http://gerrit.minix3.org/2973 mined1.c: remove i386 guard around escape sequences.        
   http://gerrit.minix3.org/2974 mined: clean-up trailing whitespace.        

Thanks for the contributions!


Regards, 

Lionel

**Comment by sambuc** [comment]
@tcort Hello, can you go on gerrit.minix3.org and login, I might have a problem as you have an old account which needs to be upgraded.

**Comment by tcort** [comment]
@sambuc okay, I logged in, but it seems to have created a new account for me. It says the account was created today. In the past I used my Google account to log in and it seems that the new version only supports logging in with github. Whenever I go to one of my recent changes using the links above I get 500 Internal Server error. Changes from last year seem to load okay... http://gerrit.minix3.org/#/c/1427/

**Comment by sambuc** [comment]
it's ok, Google is / has stopped providing an OpenID service, at least as we need it for gerrit.

Which is one of the reasons to use github instead, plus (as soon as the plugin is fixed to the latest github API) will also allow us to directly import pull request from the gerrit web interface.

Now it should be fixed, as well as all your previous commits / messages should be linked to your new account.

I am going to retrigger the jenkins build, and your commits should - finally! - be merged.

Thanks!

**Pull request closed without merging**
