### PR TITLE
x86_hdimage creates an efi bootable image now

### PR DESCRIPTION
**Pull request by rlfnb**
Test it via:

EFI_SIZE=$((128_(2_*20) )) bash releasetools/x86_hdimage.sh

### CODE REVIEW

**Comment by antoineL** [comment]
Nice work.
Just a question from an EFI4unix newbie: it seems to me (some version of) GRUB is required, is it correct? Or shall this changeset add Grub to the MINIX code base (much like there is already Binutils or GCC)?

**Comment by boricj** [comment]
@antoineL From what I see, GRUB is fetched over the network, just like U-Boot.

Glancing over the patch, I have some small comments :
* It's better to use NetBSD's `makefs` than the host's `mtools` for building FAT32 partitions as `makefs` will always be available and it won't require ugly `dd` hacks. Check https://github.com/boricj/minix/blob/61569864b0ed79e0606899e66dd9d1f370abc258/releasetools/arm_sdimage_rpi.sh#L139 for an example.
* GRUB should be cloned under `releasetools/` to keep things consistent with how U-Boot is handled.
* You should rebase your branch on top of master rather than merging with master. 

One thing that worries me is that MINIX 3 is completely unaware of UEFI. I'll have to look more deeply into it to be sure, but I wonder if this technically violates UEFI specifications (especially regarding runtime services). It will probably work fine most of the time in practice, but given how brittle and buggy some UEFI implementations are...

**Comment by antoineL** [comment]
Le 26/06/2016 à 14:01Z, Jean-Baptiste Boric wrote:
> @antoineL From what I see, GRUB is fetched over the network, just like U-Boot.

Good point.

> Glancing over the patch, I have some small comments :
> * It's better to use NetBSD's `makefs` than the host's `mtools` for building FAT32 partitions
> as `makefs` will always be available and it won't require ugly `dd` hacks.

Nice to see nbmakefs is built with "msfos" file system support, even
while MINIX does not support it ;-)


> One thing that worries me is that MINIX 3 is completely unaware of UEFI.
> I'll have to look more deeply into it to be sure, but I wonder if this
> technically violates UEFI specifications (especially regarding runtime
> services).

Is it a real problem? To shut the machine down or reboot, right?

Furthermore, the problem is that I do not believe there is a clear path
in the Multiboot protocol v1 to pass the address of runtime_services to
the real OS, so no real way for MINIX (or any other client) to invoke
the runtime services. Once that "little" problem is solved, it would be
pretty easy to store that address inside kernel space, add a new
SYS_GETINFO vector, add a new driver to load dynamically (probably named
efivars) and you are done... except that MINIX won't be able to mount
the EFI system partition, so everything will be much more complex in
practice, like requiring mtools.

> It will probably work fine most of the time in practice, but given how
> brittle and buggy some UEFI implementations are...

I feel a more real problem is that the support is limited to "IA32"
platform, which is a very limited part of the UEFI world as it exists.
I guess ARM UEFI, which is similarly a small world, could be added which
could be a win; but it won't address the point that the large majority
of UEFI machines are using the "X64" platform, which is not handled
(since it needs a 64-bit compiler+toolchain to be built.)

Anyway, it is a start.


Antoine

**Comment by boricj** [comment]
> Is it a real problem? To shut the machine down or reboot, right?

And a few other things like the RTC. But beyond runtime services, the real issue is that an UEFI system doesn't have to be IBM PC-compatible (a non-UEFI system with ACPI doesn't have to either, but stumbling across one is far less likely).

The most glaring example I am aware of is the MinnowBoard Max, where the lack of VGA text mode when not using the CSM blew up TTY, taking the system down with it. I wrote a patch to deal with it a while ago, but it didn't get picked up for some reason. Another thing if I recall correctly is that (except for the first one) all 16650 UARTs on that board are memory-mapped instead of being where they would be traditionally.

It's not specific to UEFI systems since we're supposed to parse ACPI tables instead of hard-coding 35 years old stuff, but the situation will only get worse with time as IBM PC compatibility becomes totally irrelevant thanks to UEFI.

Maybe it's time to prune hard-coded references throughout MINIX and make ACPI mandatory, but I think I'm wandering waaay off-topic now.

> I guess ARM UEFI, which is similarly a small world, could be added which could be a win

Before that, we really need flat device tree support (for the same reasons we need to parse ACPI tables). I don't think lack of UEFI support is a problem on ARM, everyone is more or less sticking with U-Boot or booting straight to the kernel for now.

> but it won't address the point that the large majority of UEFI machines are using the "X64" platform, which is not handled

I agree, but porting to x64 is going to be a huge undertaking... Maybe for MINIX 4 ? :-)

**Comment by antoineL** [comment]
Le 26/06/2016 à 19:46Z, Jean-Baptiste Boric écrivit :
> I'm wandering waaay off-topic now.

+1 && metoo  :-)

**Comment by dcvmoole** [comment]
The patch sounds good but don't know enough about the details here to say whether it's ready for merging. Given that some comments were made here, @rlfnb do you want to process those comments first or rather have it merged as is? What do others think? I'm neutral and fine with anything here. :)

> The most glaring example I am aware of is the MinnowBoard Max, where the lack of VGA text mode when not using the CSM blew up TTY, taking the system down with it. I wrote a patch to deal with it a while ago, but it didn't get picked up for some reason.

@boricj that is interesting - I believe @rlfnb has been talking about the same problem. If I'd seen a patch for this I'd have merged it. I still would like to, assuming it is also what @rlfnb needs. Where did you post it?

**Comment by boricj** [comment]
> What do others think? I'm neutral and fine with anything here. :)

I'd say cherry-pick the first patch in #134 (`Replace fetch_u-boot.sh with checkout_repo.sh`) in this pull request and use `checkout_repo.sh` to clone GRUB in `${RELEASETOOLSDIR}` with a fixed revision.

But I'm probably nitpicking way too much.

> @boricj that is interesting - I believe @rlfnb has been talking about the same problem. If I'd seen a patch for this I'd have merged it. I still would like to, assuming it is also what @rlfnb needs. Where did you post it?

In the minix3 group, subject `Minix3 failure to lack of vga text`. It only deals with TTY, the kernel will still write to the VGA card on shutdown if I remember correctly. Here's a direct link to it : https://groups.google.com/group/minix3/attach/22881e6506683/0001-tty-add-no_vga-option.patch?part=0.1&view=1

Since it was only meant for quick'n dirty troubleshooting someone else's hardware I didn't submit the patch for inclusion.

There might be other troubleshooting patches I wrote in the same vein, but the only one I can think of now is VESA console text mode-setting in the NetBSD bootloader. Which is mostly useless since pretty much no recent VESA implementations bother to support these.

**Comment by antoineL** [comment]
Well, I tested a bit of it on OpenBSD (why not?), and I found the building of `grub` (which is indeed integrated) to be rather suboptimal: `autoheader.sh` relies on `bash` (OK, this can be probably skipped by invoking with `sh`) and then on `python`, perhaps hidden behind `$PYTHON`.
I happened to not have `python` installed so I stopped there; however, the building of `grub` might ask for several tools besides the "usual" ones, and I wonder whether the cost of requiring these tools to be installed "just" to build the EFI boot loader is justified?
The same point apply for `mtools` but at least it is (?) available as a binary package.
Also I feel the list of tools required ought to be documented (hint to start: https://www.freshports.org/sysutils/grub2-efi).

**Comment by rlfnb** [comment]
thanks for commenting so far, I appreciate the feedback. I addressed one issue and changed workdir for grub to $RELEASEDIR. Will look later, which git commit should be the "golden" one for building the efi loader. Will change mtools commands to netbsd makefs, too.

Furthermore, let me give my two cents, too:

1. I can add the patch proposed by @boricj, but TBH I believe we should do it right the first time. So, the PR contains everything to boot the minix kernel via uefi bit. Next step should be to substitute all places, where minix writes to console via bios int 10 (vga text) by using 0xB8000 as an address. So, we do not need any special boot options because we get rid of additional BIOS INTs.

2. Minix3 does not know anything about UEFI and maybe its good. Bernd Onasch already pointed out at Minixcon2016 how to [hide boot loader specifics](http://www.minix3.org/conference/2016/slides/Onasch.pdf) from the kernel. From POV, starting with EFI gives us the chance to streamline the whole booting process and how to deal with informations given by the boot loaders to the kernel.

Personally, I see it as a kind of kick-off modernizing Minix and I think, it takes much effort, so I would also like to invite everyone helping to modernize minix.

**Comment by dcvmoole** [comment]
> In the minix3 group, subject Minix3 failure to lack of vga text
Ah yes. I did see this, even replied, and then completely forgot. My bad, sorry :( I'm afraid that patch is logically flawed and will cause buffer underflows in the serial line handling code, though. The alternative I suggested back then is still the right way forward, I think..

**Comment by dcvmoole** [comment]
> Will look later, which git commit should be the "golden" one for building the efi loader. Will change mtools commands to netbsd makefs, too.

Alright.

> I can add the patch proposed by @boricj, but TBH I believe we should do it right the first time.

I don't understand what you mean here: wouldn't rebasing your work on top of that patch be even better, since that script is more generic? What is not "right" about that? After having missed a night's sleep I shouldn't even be writing comments, so I'll be very clear that this is not criticism, just curiosity.

**Comment by rlfnb** [comment]
ok, added the patch from @boricj from my POV, everything's ready to commit. When its in master, I'll write a short how to in the wiki.

**Comment by boricj** [comment]
> Next step should be to substitute all places, where minix writes to console via bios int 10 (vga text) by providing a framebuffer-based console. Its more effort, but then, we are definitely safe and can also address the issues with higher console resolutions for free.

A better solution would be to support both text and framebuffer console, at least for the short term. I'd prefer to have the text console around as a fallback until the (yet-to-be-done) framebuffer console is bug-free.

> ok, added the patch from @boricj

I think @dcvmoole meant to rebase this pull request on top of the first patch of #134 (Replace fetch_u-boot.sh with checkout_repo.sh) and use `checkout_repo.sh` to checkout GRUB. If the no_vga patch indeed causes buffer underflows that patch can't be merged in this state anyway.

By the way, use `git cherry-pick` when cherry-picking commits or `git-am` when applying patches, otherwise you will change authorship of commits (891eade credits you as the author, but I'm the one who wrote the patch).

**Comment by rlfnb** [comment]
Wont steal ideas from others, stated also in the comment, who wrote it. Nevertheless, @dcvmoole will not add it at all if I understood it correctly. 

Framebuffer based console would be great and I believe it's not too difficult.

Hope it's fine now to merge it in without the vga patch.

**Comment by dcvmoole** [comment]
> I think @dcvmoole meant to rebase this pull request on top of the first patch of #134 (Replace fetch_u-boot.sh with checkout_repo.sh) and use checkout_repo.sh to checkout GRUB.

Indeed, but I guess this is.. not happening right now? Oh well, should be an easy change later. @boricj I can already merge that particular patch if you think that's a good idea?

**Comment by boricj** [comment]
> Indeed, but I guess this is.. not happening right now?

This pull request was closed and #142 was opened with a cleaned-up version, probably due to lack of familiarity with Git.

> @boricj I can already merge that particular patch if you think that's a good idea?

OK.

**Pull request closed without merging**
