### PR TITLE
Port netbsd dd

### PR DESCRIPTION
**Pull request by Tookmund**
I can squash these commits when ready
Everything has been moved over but dd test 2 fails:
ddtest

I'm still sort of new to all this, why is the test failing?

### CODE REVIEW

**Comment by tcort** [comment]
I'm looking at this on my phone, so maybe I don't see it, but I think you may have missed the old dd man page, minix/man/man1/dd.1 and the reference to it in minix/man/man1/Makefile

**Comment by Tookmund** [comment]
Yep didn't see that there. Thanks!

**Comment by Tookmund** [comment]
For some reason, my changes are no longer showing up in my pull requests. I went back and added the files to the mi list and also removed the old man page, but it doesn't show up...

**Comment by dcvmoole** [comment]
For what it's worth, one reason the test is failing is that MINIX3 doesn't support the /dev/fd/ directory at all. So, that has nothing to do with dd(1).

**Comment by sambuc** [comment]
I have squashed the commits, and changed the commit message, and fixed a couple of minor issues.

Here is the result, tell me if this is OK for you: 
  https://github.com/sambuc/minix/commit/5e4cbb93622e87993fa25698bc486e1b731f29ad

I will wait for your OK before submitting that commit.


Regards

**Comment by Tookmund** [comment]
Looks fine to me! Thx for fixing it up!

**Comment by sambuc** [comment]
Hi, 

submitted as: http://gerrit.minix3.org/2986

**Pull request closed without merging**
