### PR TITLE
Replace the MINIX 3 network stack

### PR DESCRIPTION
**Pull request by dcvmoole**
Now that I have locally tested as much as I reasonably can, as far as I am concerned, this branch is ready to be merged. Any pre-merge testing by others would be highly appreciated as well. Highlights of this branch:

- first-class VFS support for socket-type file objects instead of a series of libc kludges;
- a socket driver library (libsockdriver) and a socket event dispatching library (libsockevent);
- a new, POSIX-compliant implementation of the UNIX Domain Sockets service (UDS);
- a new TCP/IP service (LWIP), built upon the core of the lwIP project;
- proper support for the BSD socket API and the BSD network management API;
- full-blown support for IPv6;
- replacement of old MINIX networking userland with modern NetBSD networking userland;
- network driver protocol extensions, from reporting link status to checksum offloading;
- auto-starting of plug-and-play network drivers;
- NetBSD-style rc-script based network initialization;
- about 18 KLoC worth of new tests (test90-94).

### CODE REVIEW

**Comment by boricj** [comment]
If plug-and-play network drivers are automatically started on boot, it should be easy enough to perform installation by downloading the distribution sets over the network. A stripped down, installation-only USB ramdisk image might be doable...

I am far too overworked to test this at the moment, but good job!

**Comment by dcvmoole** [comment]
Thanks! :) and indeed, that sounds good. Somewhat related: we're now also getting really close to having networking working on the installation CD; the only thing that is missing is a writable /etc, for /etc/resolv.conf. Unfortunately, /etc is a bit big to put on a ramdisk-backed partition like we do for some other dirs, to the point that at least the lance driver can no longer allocate its buffers in the low-memory region at least (..I tried). A unionfs-like thing would be really cool for this, although we also need a reserved pool of low memory regions for such drivers.. ahh so much to do :)

**Comment by boricj** [comment]
I gave a bit of thought for a MINIX unionfs-like and I remembered an interesting thing. 

isofs is actually a half-baked, read-only directory tree cache overlayed on top of ISO 9660 that will grow until the entire tree is in memory. This has bothered me ever since I rewrote it, as I've always thought of it as an ugly performance hack that does not belong there.

By making a cleaned-up, dedicated, read-write version of this we could basically turn it into Linux's ramfs. I can see several applications for this :
- by allowing a read-only file system as an optional backing store, we could turn the installation CD into a proper live CD like Knoppix,
- even if we somehow don't want in-memory read-write capability for a particular file system, it could act as a directory tree cache to speed up slow, read-only file systems like ISO 9660,
- it could replace the MFS ramdisk during early boot if we extract a cpio archive or equivalent inside it,
- it would return isofs into a sane state.

If I end up doing this, I'll wait until the graph/node/edge file system thing announced at MINIXcon materializes before attempting it.

Also, it's probably not a good idea to convert isofs to that framework with the directory cache hack in place, if only because that part would be obsoleted by the cachefs idea when it will get implemented.

**Comment by dcvmoole** [comment]
> If I end up doing this, I'll wait until the graph/node/edge file system thing announced at MINIXcon materializes before attempting it.

Haha, I guess I should get on with that then.. although I can't promise it will be generic enough to be useful at least directly for your (very interesting) idea here. But we'll see.

Back on topic, I forgot to mention that the branch requires a bump of sizes of the jenkins x86 debug build. I have successfully been using the following values instead of the ones used by jenkins now:

```
export BOOTXX_SECS=32
export FAT_SIZE=20480
export IMG_SIZE=4966055936 # ROOT+HOME+USR+16k
export ROOT_SIZE=536854528
export HOME_SIZE=134217728
export USR_SIZE=4294967296
```

**Comment by boricj** [comment]
I tried to build master with `MKDEBUG=yes MKDEBUGLIB=yes`, but it fails with:

```
======  2 missing files in DESTDIR  ========
Files in flist but missing from DESTDIR.
File wasn't installed ?
------------------------------------------
./usr/libdata/debug/usr/libexec/httpd.debug
./usr/libdata/debug/usr/sbin/lwresd.debug
========  end of 2 missing files  ==========
```

The regression obviously came from this pull request. `httpd.debug` is marked obsolete in the NetBSD set files and `lwresd.debug` does not exists (`lwresd` is declared as a symlink to `named` in bind's `named` Makefile).

As a side note, I've noticed that Gerrit's debug builds merely have `DBG=-g` set, perhaps we should change that to `MKDEBUG=yes MKDEBUGLIB=yes` instead to catch these kind of mistakes in the future?

**Comment by dcvmoole** [comment]
Good catch, thanks! I did test with MKDEBUG/MKDEBUGLIB, but I guess I made some small changes after doing so and broke it after all. I'll submit a patch as soon as gerrit is fully up and running again.

**Comment by dcvmoole** [comment]
Fixed in 62cf0e1226d25a9da8f0cbcaaf52f3f5a7488e5f, thanks again.

**Comment by sambuc** [comment]
I will give it a try, and switch the -g builds to MKDEBUG/MKLIBDEBUG=yes, if the tests are OK.

If the result is the same, for me there is no problem in using this for `-g`. I will need to see how it behaves with the COPTS/DBG variables to make sure we can still use those as well.

**Pull request merged**
