### PR TITLE
Import rump

### PR DESCRIPTION
**Pull request by boricj**
This is an initial stab at importing rump into MINIX. For now I'm focusing on building the rump kernel by importing parts of the NetBSD kernel. It's going surprisingly well so far.

The biggest problem so far is the lack of pthread support, which the reference POSIX hypervisor requires. This blocks at least fs-utils and the standard tests ; writing a homegrown hypervisor will probably be required anyway in order to use rump in the service layer. 

Note : this is an early work-in-progress. Without a hypervisor the libraries are useless, so there's no point in merging this for now. I'm opening this pull request to gather feedback.

### CODE REVIEW

**Comment by r0ller** [comment]
Hi Jean-Baptiste,

Unfortuantely, I cannot do more than welcome this move:) I guess you've checked some earlier discussions of the topic but if it's not the case, Lionel may give you some hint and I guess you can still reach out to Justin (@NetBSD) as well:

https://groups.google.com/d/msg/minix3/S-8-9sYeCow/VI-p2XF40wkJ
https://groups.google.com/d/msg/minix3/9FNGf_Z2ofY/XG_UW_wgt-0J

Regards,
r0ller

**Comment by boricj** [comment]
I am operating under the assumption that _building_ rump kernel components inside the MINIX source tree shouldn't be too difficult, since it's mostly just self-contained NetBSD kernel code and headers that MINIX ignores (almost) completely.

However, _using_ those components in practice won't be as easy. I'm worried that MINIX's POSIX implementation isn't advanced enough to allow a straightforward import of the userland stuff and a fair amount of glue code will be required to use rump in the service/driver layer...

**Comment by sambuc** [comment]
This is something we have been looking for a very long time.

I have the same worries as you, which is why I guess the first step is to get the user land tools working, and then we can contact Justin Cormack for some pointers on how best to write the glue code between rump and the kernel. Once we get drivers running on an anykernel, then we can look into how best to connect them to the various driver libraries we have.

Justin was interested we we looked into it back at EuroBSDCon 2014, so he might be willing to answer a couple of questions.


Kind regards,

Lionel

**Comment by boricj** [comment]
The good news is that I've managed to get some binaries (`rump_server`, `rump.sysctl`, `rump_sysvbfs` among others) to link and execute, for some loose definition of the word "execute".

The bad news is that it seems the fiber implementation of `librumpuser` can't handle running rump servers. When launching `rump_server` I get a reasonable rump kernel dmesg output, but it will not actually act as a server since `rumpuser_sp_init` in `rumpfiber_sp.c` is just a stub.

I don't know if rump client binaries work (`rump.sysctl`...), but at least they properly complain that they can't connect to a nonexistent server.

**Pull request closed without merging**
