### PR TITLE
Removed unused variables and cleaned some code whitespaces

### PR DESCRIPTION
**Pull request by benmezger**
Just some minor removal of unused variables.
Hopefully the removal of whitespaces in the comments is not a issue, since it won't really matter for an editor, but let me know if I should revert that.

### CODE REVIEW

**Comment by dcvmoole** [comment]
Thank you for your contribution! We are currently figuring out what to merge in which order, but will get to your patch ASAP. Please bear with us in the meantime :) -David/Saturn

**Comment by benmezger** [comment]
Great, let me know when you merge the rest, so perhaps I could resync my repo and give you a more up to date code.

**Comment by dcvmoole** [comment]
Will do, thanks!

**Comment by sambuc** [comment]
This has been merged as:
 - 81ae2bc455a73c05792f181d5497cdbd33f3c135
 - 9f7f0ad073a34bff0457b448a521376251622b4d
 - afc65e92aa785da3cd6262780636e649f57ae9c3
 - 19155598849a2c33c200f54f5f6f4fd781276c9b 

Thank you for the contribution!

**Pull request closed without merging**
