### PR TITLE
Improve the process for GNU tools

### PR DESCRIPTION
**Pull request by antoineL**
Do not run configure on each run when MKUPDATE=yes
The .WAIT serialization instruction between fetching and other
configure sources was raising a new run of configure at each
compilation. Avoid it by using two rules.

Change-Id: Ie24950ccbb5c5067f3c1ea57b7bd8294e4c9445e

### CODE REVIEW

**Comment by antoineL** [comment]
Just seen the gerrit build is broken.
I am working on a 2nd version right now.
It will also cover the cases when one builds texinfo or binutils for
MINIX without building the tools before.

**Comment by antoineL** [comment]
Resubmitted after correction

**Comment by antoineL** [comment]
Re-resubmitted! This time I really believe I corrected the bug (which was that the "fetching" logic was brought *after* being needed by the dependency rule for build/gas/m68k-parse.c)

**Comment by sambuc** [comment]
Thanks, this has been merged as a150b26ee803b20080e65cd7a048322ba498f6bf

**Pull request closed without merging**
